merge

diff --git a/zsh/autoload/g4d b/zsh/autoload/g4d
--- a/zsh/autoload/g4d
+++ b/zsh/autoload/g4d
@@ -1,1 +1,68 @@
-../g4d/g4d
+# vi: ft=zsh
+local force
+zparseopts -D -- f=force
+
+if ! gcertstatus --nocheck_ssh --quiet
+then
+  >&2 echo "Please run gcert."
+  return
+fi
+
+if [[ $# == 0 ]]
+then
+  if [[ -n $CITC_ROOT ]]
+  then
+    cd $CITC_ROOT
+    return 0
+  else
+    return 1
+  fi
+fi
+
+local citclist=($(command ls /google/src/cloud/$USER))
+local fullpath
+local arg=(${(s/@/)1})  # get alias if it exists
+local target=$arg[1]
+local alias_=$arg[2]
+
+if [[ -n $citclist[(r)$target] ]]
+then
+  full_path="/google/src/cloud/$USER/$target/google3"
+elif [[ "$target" =~ ^[0-9]+$ ]]
+then
+  maybe_full_path=$(p4 g4d $target 2>/dev/null)
+  if (( $? ))
+  then
+    full_path=/google/src/files/"$target"/depot/google3
+  else
+    full_path=$(p4 g4d $target | tr -d '\r')
+  fi
+
+elif (( $+force[1] ))
+then
+  full_path=$(p4 g4d -f $target|tail -1|tr -d '\r')
+fi
+
+
+if [[ -n $full_path ]]
+then
+  if [[ -n $alias_ ]]
+  then
+    if [[ $alias_ =~ "^[0-9]+$" ]]
+    then
+      full_path="${full_path:h}/.snapshot/${alias_}/google3"
+    else
+      typeset +g -A g4d_aliases
+      g4d_aliases=(${=${${(@M)${(f)"$(cat $HOME/.g4d 2>/dev/null)"}:#alias @*}#alias @}})
+      if (( $+g4d_aliases[$alias_] ))
+      then
+        full_path="$full_path/$g4d_aliases[$alias_]"
+      else
+        >&2 echo "Alias $alias_ was not found in $HOME/.g4d"
+      fi
+    fi
+  fi
+  builtin cd $full_path
+else
+  >&2 echo "Cannot cd into $target"
+fi
diff --git a/zsh/g4d/g4d b/zsh/g4d/g4d
--- a/zsh/g4d/g4d
+++ b/zsh/g4d/g4d
@@ -30,10 +30,17 @@ then
   full_path="/google/src/cloud/$USER/$target/google3"
 elif [[ "$target" =~ ^[0-9]+$ ]]
 then
-  full_path=$(p4 g4d $target)
+  maybe_full_path=$(p4 g4d $target 2>/dev/null)
+  if (( $? ))
+  then
+    full_path=/google/src/files/"$target"/depot/google3
+  else
+    full_path=$(p4 g4d $target | tr -d '\r')
+  fi
+
 elif (( $+force[1] ))
 then
-  full_path=$(p4 g4d -f $target)
+  full_path=$(p4 g4d -f $target|tail -1|tr -d '\r')
 fi
 
 
@@ -41,13 +48,18 @@ if [[ -n $full_path ]]
 then
   if [[ -n $alias_ ]]
   then
-    typeset +g -A g4d_aliases
-    g4d_aliases=(${=${${(@M)${(f)"$(cat $HOME/.g4d 2>/dev/null)"}:#alias @*}#alias @}})
-    if (( $+g4d_aliases[$alias_] ))
+    if [[ $alias_ =~ "^[0-9]+$" ]]
     then
-      full_path="$full_path/$g4d_aliases[$alias_]"
+      full_path="${full_path:h}/.snapshot/${alias_}/google3"
     else
-      >&2 echo "Alias $alias_ was not found in $HOME/.g4d"
+      typeset +g -A g4d_aliases
+      g4d_aliases=(${=${${(@M)${(f)"$(cat $HOME/.g4d 2>/dev/null)"}:#alias @*}#alias @}})
+      if (( $+g4d_aliases[$alias_] ))
+      then
+        full_path="$full_path/$g4d_aliases[$alias_]"
+      else
+        >&2 echo "Alias $alias_ was not found in $HOME/.g4d"
+      fi
     fi
   fi
   builtin cd $full_path
